[package]
name = "nanners-sys"
version = "0.0.1"
authors = ["Dave Herman <dherman@mozilla.com>"]
license = "MIT"

# libnanners.a gets linked in with this package
links = "nanners"

# this script builds libnanners.a
build = "build.rs"

[build-dependencies]
gcc = "0.3"
